# Generated by Django 5.0.4 on 2024-05-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
