# Generated by Django 5.0.4 on 2024-05-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
