# Generated by Django 5.0.4 on 2024-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseña',
            name='fecha_reseña',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
