# Generated by Django 5.0.4 on 2024-05-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_reseña_fecha_reseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Ordenadores', 'ordenadores'), ('Portatiles', 'portatiles'), ('Moviles', 'moviles'), ('Perifericos', 'perifericos'), ('Componentes', 'componentes'), ('Accesorios', 'accesorios')], max_length=50),
        ),
    ]
