# Generated by Django 5.0.4 on 2024-06-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='especidicaciones',
            new_name='especificaciones',
        ),
    ]
