# Generated by Django 5.0.4 on 2024-06-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_producto_imagen_imagenproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reseña',
        ),
    ]
