# Generated by Django 5.0.4 on 2024-06-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_pedido_estado_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reembolso',
        ),
    ]
