# Generated by Django 5.0.4 on 2024-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_reembolso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito')], max_length=50),
        ),
    ]
